### ISSUE TITLE
Console App - Languages in query options not capitalised

### ISSUE THREAD

**Issue by LukasP23** [Craig180885-napier/Group-Project#101]
**Describe the bug**
When opening the console app and being prompted to select a query, the languages listed in query option 9 are not capitalised.

**To Reproduce**
- Open console app

**Expected behavior**
The languages listed in query 9 are capitalised.

**Screenshots**
In comments

**Comment by Craig180885-napier** [comment]
![9 1 - 1](https://user-images.githubusercontent.com/78031636/115603300-e3e47280-a2d7-11eb-901d-bc93e0c4a143.jpg)
