### ISSUE TITLE
'q' does not exit during 'y' or 'n' phase of console app

### ISSUE THREAD

**Issue by LukasP23** [Craig180885-napier/Group-Project#102]
**Describe the bug**
The user should be able to enter 'q' to exit the console app at any stage of the process. However when at the 'would you like to run another query' stage of the process, the user can only enter 'y' or 'n'.

**To Reproduce**
- Open console app
- Follow required steps to successfully run a query
- when asked if you would like to run another query enter 'q'

**Expected behavior**
Entering 'q' should exit the console app.

**Screenshots**
In comments

**Comment by Craig180885-napier** [comment]
![Q to exit](https://user-images.githubusercontent.com/78031636/115603555-3756c080-a2d8-11eb-80dc-8e13fbded12c.jpg)
